# Generated by Django 5.2.13 on 2026-04-29 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0017_alter_userprofile_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(blank=True, choices=[('', 'Не указано'), ('O-', 'O−'), ('O+', 'O+'), ('A-', 'A−'), ('A+', 'A+'), ('B-', 'B−'), ('B+', 'B+'), ('AB-', 'AB−'), ('AB+', 'AB+')], max_length=4)),
                ('allergies', models.TextField(blank=True)),
                ('chronic_conditions', models.TextField(blank=True)),
                ('insurance_info', models.CharField(blank=True, max_length=255)),
                ('emergency_contact', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_record', to='core.familymember')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('dosage', models.CharField(blank=True, max_length=80)),
                ('frequency', models.CharField(choices=[('daily', 'Ежедневно'), ('twice_daily', '2 раза в день'), ('thrice_daily', '3 раза в день'), ('weekly', 'Еженедельно'), ('as_needed', 'По необходимости')], default='daily', max_length=20)),
                ('times', models.CharField(blank=True, help_text='Comma-separated HH:MM, e.g. 08:00,20:00', max_length=120)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='core.familymember')),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
