# Generated by Django 6.0.1 on 2026-01-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_telegramprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='remind_days_before',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
