# Generated by Django 6.0.1 on 2026-01-28 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_familyinvitation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
    ]
