# Generated by Django 6.0.1 on 2026-01-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymember',
            options={'ordering': ['display_order', 'last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='familymembership',
            options={'ordering': ['display_order', 'joined_at']},
        ),
        migrations.AddField(
            model_name='familymember',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='familymembership',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
