# Generated by Django 6.0.1 on 2026-01-28 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_familymember_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='parent1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_from_parent1', to='core.familymember'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='parent2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_from_parent2', to='core.familymember'),
        ),
    ]
