# Generated by Django 6.0.1 on 2026-01-28 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_familymember_parent1_familymember_parent2'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse_of', to='core.familymember'),
        ),
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('birthday', 'День рождения'), ('holiday', 'Праздник'), ('family', 'Семейное событие'), ('other', 'Другое')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='familyinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('revoked', 'Отозвано')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='familymembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('member', 'Участник')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Нужно сделать'), ('in_progress', 'В процессе'), ('done', 'Готово')], default='todo', max_length=20),
        ),
    ]
