# Generated by Django 6.0.1 on 2026-01-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_familymember_spouse_alter_event_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='in_tree',
            field=models.BooleanField(default=False),
        ),
    ]
