# Generated by GitHub Copilot on 2026-01-29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_telegramprofile_confirmation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("middle_name", models.CharField(blank=True, max_length=80)),
                ("relation", models.CharField(blank=True, max_length=80)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("address_home", models.CharField(blank=True, max_length=255)),
                ("address_country_house", models.CharField(blank=True, max_length=255)),
                ("socials", models.TextField(blank=True, help_text="Ссылки на соцсети")),
                ("workplace", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("parent1_name", models.CharField(blank=True, max_length=120)),
                ("parent2_name", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
