# Generated by GitHub Copilot on 2026-01-29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="parent1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles_as_parent1",
                to="core.familymember",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="parent2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles_as_parent2",
                to="core.familymember",
            ),
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="parent1_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="parent2_name",
        ),
    ]
