# Generated by GitHub Copilot on 2026-01-29

from django.db import migrations, models
from django.utils import timezone


def fill_birth_dates(apps, schema_editor):
    UserProfile = apps.get_model("core", "UserProfile")
    today = timezone.localdate()
    UserProfile.objects.filter(birth_date__isnull=True).update(birth_date=today)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_message_options"),
    ]

    operations = [
        migrations.RunPython(fill_birth_dates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="userprofile",
            name="birth_date",
            field=models.DateField(),
        ),
    ]
