# Generated by Codex on 2026-05-16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_message_attachment_message_attachment_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="familyphoto",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photos",
                to="core.event",
            ),
        ),
        migrations.DeleteModel(
            name="TelegramProfile",
        ),
    ]
