# Generated by Django 5.2.13 on 2026-05-18 10:54

from django.db import migrations, models


def set_birthday_recurrence(apps, schema_editor):
    Event = apps.get_model("core", "Event")
    Event.objects.filter(kind="birthday").update(recurrence="yearly")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_external_messenger_photo_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrence',
            field=models.CharField(choices=[('none', 'Не повторять'), ('daily', 'Каждый день'), ('weekly', 'Каждую неделю'), ('monthly', 'Каждый месяц'), ('yearly', 'Каждый год')], default='none', max_length=20),
        ),
        migrations.RunPython(set_birthday_recurrence, migrations.RunPython.noop),
    ]
