# Generated by Django 5.2.13 on 2026-04-29 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0017_alter_userprofile_birth_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capsule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField(blank=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='capsules/')),
                ('reveal_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('delivered', 'Доставлено'), ('cancelled', 'Отменено')], default='scheduled', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capsules_authored', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capsules', to='core.family')),
                ('recipient_member', models.ForeignKey(blank=True, help_text='Optional: tie reveal to a specific tracked relative (e.g. for an 18th birthday).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capsules_for_member', to='core.familymember')),
                ('recipients_users', models.ManyToManyField(blank=True, related_name='capsules_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reveal_at'],
            },
        ),
    ]
