from django.urls import path

from . import views as _v
from .views import (
    events,
    families,
    family_members,
    home,
    family_delete,
    family_detail,
    family_edit,
    family_member_remove,
    family_tree,
    family_tree_graph,
    family_tree_relations_update,
    family_tree_order_update,
    family_tree_edit,
    invitation_accept,
    invitation_revoke,
    telegram_confirm,
    user_suggest,
    event_delete,
    event_edit,
    member_delete,
    member_edit,
    member_detail,
    user_detail,
    messages,
    message_delete,
    profile_edit,
    signup,
    task_detail,
    task_delete,
    task_edit,
    tasks,
    goals,
    goal_detail,
    event_detail,
    family_album,
)


urlpatterns = [
    path("", home, name="home"),
    path("signup/", signup, name="signup"),
    path("profile/", profile_edit, name="profile_edit"),
    path("families/", families, name="families"),
    path("families/<int:family_id>/", family_detail, name="family_detail"),
    path("families/<int:family_id>/members/<int:membership_id>/remove/", family_member_remove, name="family_member_remove"),
    path("families/<int:family_id>/edit/", family_edit, name="family_edit"),
    path("families/<int:family_id>/delete/", family_delete, name="family_delete"),
    path("invites/<uuid:token>/accept/", invitation_accept, name="invitation_accept"),
    path("invites/<int:invitation_id>/revoke/", invitation_revoke, name="invitation_revoke"),
    path("telegram/confirm/<uuid:token>/", telegram_confirm, name="telegram_confirm"),
    path("users/suggest/", user_suggest, name="user_suggest"),
    path("members/", family_members, name="members"),
    path("family-tree/", family_tree, name="family_tree"),
    path("family-tree/graph/", family_tree_graph, name="family_tree_graph"),
    path("family-tree/edit/", family_tree_edit, name="family_tree_edit"),
    path("family-tree/order/", family_tree_order_update, name="family_tree_order"),
    path("family-tree/relations/", family_tree_relations_update, name="family_tree_relations"),
    path("members/<int:member_id>/edit/", member_edit, name="member_edit"),
    path("members/<int:member_id>/", member_detail, name="member_detail"),
    path("members/user/<int:user_id>/", user_detail, name="user_detail"),
    path("members/<int:member_id>/delete/", member_delete, name="member_delete"),
    path("events/", events, name="events"),
    path("events/<int:event_id>/", event_detail, name="event_detail"),
    path("events/<int:event_id>/edit/", event_edit, name="event_edit"),
    path("events/<int:event_id>/delete/", event_delete, name="event_delete"),
    path("tasks/", tasks, name="tasks"),
    path("tasks/<int:task_id>/", task_detail, name="task_detail"),
    path("tasks/<int:task_id>/edit/", task_edit, name="task_edit"),
    path("tasks/<int:task_id>/delete/", task_delete, name="task_delete"),
    path("goals/", goals, name="goals"),
    path("goals/<int:goal_id>/", goal_detail, name="goal_detail"),
    path("album/", family_album, name="family_album"),
    path("messages/", messages, name="messages"),
    path("messages/<int:message_id>/delete/", message_delete, name="message_delete"),
    path("profile/ui/", _v.ui_set_pref, name="ui_set_pref"),
]
