# Generated by Django 5.2.13 on 2026-05-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='unit',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
