# Generated by Django 5.2.13 on 2026-05-18 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_external_messenger_photo_event'),
        ('kinnet_budget', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlists_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='share_with_family',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='shared_with_members',
            field=models.ManyToManyField(blank=True, related_name='shared_wishlist_items', to='core.familymember'),
        ),
        migrations.CreateModel(
            name='ExpenseContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_contributions', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='kinnet_budget.expense')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
